// =============================================================================
// os2/platform/contracts.hpp — 契约类型的 C++ 镜像
//
// ⚠ AUTO-GENERATED by tools/gen_contracts.py — 禁止手改（改契约源后 make contracts-gen）
// 真相源：contracts/VERSION（契约版本，OS2-API 冻结口径）
//         contracts/data-dictionary/data_dictionary.yaml（枚举/字段）
//         contracts/error-codes/error_codes.yaml（错误码全集）
//         contracts/topics/topics.yaml（主题清单，《架构说明》§8.7 机读形态）
//         contracts/idl/os2_common.idl（Command/Reply/Event/Metric，《架构说明》§6.2）
// 门禁：make contracts-check = 再生成 + 字节比对，漂移即失败（E-2 §5 门禁 D）。
// 变更流程：契约源改动走 RFC → L0 仲裁 → 重新生成提交（ADR-0012）；
//           v1.0 冻结后按版本流程（docs/reviews/2026-07-10-contract-freeze-review.md §4）。
// =============================================================================
#pragma once

#include <chrono>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <map>
#include <optional>
#include <random>
#include <string>

namespace os2 {

// ---------------------------------------------------------------------------
// 契约版本（生成自 contracts/VERSION）——OS2-API 冻结基线，页面/接口回显用真值
// ---------------------------------------------------------------------------
inline constexpr const char* kContractVersion = "1.23.0";

// ---------------------------------------------------------------------------
// 数据字典枚举（生成自 data_dictionary.yaml enums.*.cpp_type）
// ---------------------------------------------------------------------------
enum class Domain { Cai, Compute, Hmi, Ops };  // 采控/计算/人机交互/运维
enum class Criticality { A, B, C, D };  // 关键性等级
enum class Health { Ok, Degraded, Down };  // 健康状态

inline const char* to_string(Domain v) {
  switch (v) { case Domain::Cai: return "cai"; case Domain::Compute: return "compute"; case Domain::Hmi: return "hmi"; default: return "ops"; }
}
inline const char* to_string(Criticality v) {
  switch (v) { case Criticality::A: return "A"; case Criticality::B: return "B"; case Criticality::C: return "C"; default: return "D"; }
}
inline Criticality criticality_from(const std::string& s) {
  if (s == "A") return Criticality::A;
  if (s == "B") return Criticality::B;
  if (s == "C") return Criticality::C;
  return Criticality::D;
}
inline const char* to_string(Health v) {
  switch (v) { case Health::Ok: return "ok"; case Health::Degraded: return "degraded"; default: return "down"; }
}

// ---------------------------------------------------------------------------
// 错误码（生成自 error_codes.yaml；新增先改 yaml 再 make contracts-gen）
// ---------------------------------------------------------------------------
namespace errc {
inline constexpr const char* OK                         = "OS2-0000"; // common    OK
inline constexpr const char* MSG_TYPE_REJECTED          = "OS2-0002"; // common    报文类型/格式校验失败
inline constexpr const char* MSG_SIZE_EXCEEDED          = "OS2-0003"; // common    报文/字段/键数越尺寸上界
inline constexpr const char* SVC_NOT_REGISTERED         = "OS2-1001"; // registry  服务未注册
inline constexpr const char* SVC_LEASE_EXPIRED          = "OS2-1002"; // registry  心跳租约过期，实例保留并置 down
inline constexpr const char* SVC_ID_INVALID             = "OS2-1003"; // registry  运行服务标识非法
inline constexpr const char* SVC_ENDPOINT_REQUIRED      = "OS2-1004"; // registry  注册端点缺失
inline constexpr const char* REGISTRY_NOT_LEADER        = "OS2-1005"; // registry  注册中心不是当前主
inline constexpr const char* REGISTRY_INTERNAL          = "OS2-1006"; // registry  注册内部错误
inline constexpr const char* DEV_OFFLINE                = "OS2-2001"; // device    设备离线
inline constexpr const char* DEV_INTERLOCK              = "OS2-2002"; // device    互锁校验失败
inline constexpr const char* SCH_CHAIN_INVALID          = "OS2-3001"; // scheduler 服务链非法
inline constexpr const char* SCH_E2E_TIMEOUT            = "OS2-3002"; // scheduler 端到端超时
inline constexpr const char* SCH_RESOURCE_EXHAUSTED     = "OS2-3003"; // scheduler 资源预留被拒
inline constexpr const char* SCH_MISROUTED              = "OS2-3004"; // scheduler 回执来源与落位不符
inline constexpr const char* SEC_DENIED                 = "OS2-4001"; // security  越权操作被拒
inline constexpr const char* MODEL_IMPACT_INPUT_INVALID = "OS2-5001"; // model     影响查询输入未知或非法
inline constexpr const char* PROFILE_MODEL_DRIFT        = "OS2-5002"; // model     Profile 与模型权威事实不一致
inline constexpr const char* WL_INSTANCE_UNKNOWN        = "OS2-6001"; // workload  实例不在本节点清单内
inline constexpr const char* WL_SPAWN_FAILED            = "OS2-6002"; // workload  服务进程拉起失败
inline constexpr const char* WL_NOT_RUNNING             = "OS2-6003"; // workload  进程未在运行
inline constexpr const char* WL_ACTION_UNKNOWN          = "OS2-6004"; // workload  未知的进程控制动作
}  // namespace errc

// ---------------------------------------------------------------------------
// 主题清单（生成自 topics.yaml）。管理面走管理软总线，业务面走业务软总线。
// 模块间只允许通过这些主题交互 —— 这是运行时的边界铁律。
// ---------------------------------------------------------------------------
namespace topics {
// 服务注册中心
inline constexpr const char* ServiceRegister           = "os2.mgmt.service.register";            // req/rep
inline constexpr const char* ServiceHeartbeat          = "os2.mgmt.service.heartbeat";           // pub（v1.9/RFC-0009：timestamp 仅作证据；服务端接收时刻重置租约；严格大于 lease_ms 才过期）
inline constexpr const char* ServiceCatalogQuery       = "os2.mgmt.service.catalog.query";       // req/rep（v1.1/RFC-0001 分页过滤；v1.9/RFC-0009 应答附逐记录 lease_ms，发现语义仍是服务级最佳实例）
// 运维管理器
inline constexpr const char* ServiceInstanceStateQuery = "os2.mgmt.ops.service-instance.query";  // req/rep（v1.9/RFC-0009：/state.serviceInstances 的内部事实源，不参与服务发现或调度）
// 模型与数据管理器
inline constexpr const char* ImpactQuery               = "os2.mgmt.model.impact.query";          // req/rep（v1.13/RFC-0013：只读确定性影响查询；显式故障 + M7 运行事实 → 排序稳定的节点/服务/链与传播路径）
// 服务注册中心
inline constexpr const char* RegistryAnnounce          = "os2.mgmt.service.announce";            // pub（纪元广播：重启收敛，M0.9/ADR-0008）
// 设备监管器
inline constexpr const char* DeviceRegister            = "os2.mgmt.device.register";             // req/rep
inline constexpr const char* DeviceStateTopic          = "os2.mgmt.device.state";                // pub
inline constexpr const char* ProgramControlCommand     = "os2.mgmt.device.control";              // req/rep（Command→Reply）
// 资源管理器
inline constexpr const char* ResourceInventoryQuery    = "os2.mgmt.resource.inventory.query";    // req/rep
inline constexpr const char* ResourceSnapshot          = "os2.mgmt.resource.snapshot";           // pub
inline constexpr const char* ResourceReport            = "os2.mgmt.resource.report";             // pub（节点画像上报：域侧资源 Agent → 总控聚合成全局资源树，M1.3/ADR-0015）
inline constexpr const char* ResourceReserve           = "os2.mgmt.resource.reserve";            // req/rep（v1.2/RFC-0002：调度规划后预留节点份额（node_id/frac/holder/ttl_ms → accepted/reason），填充预留账本、评分即时折扣，TTL+释放双保险防泄漏）
inline constexpr const char* ResourceRelease           = "os2.mgmt.resource.release";            // req/rep（v1.2/RFC-0002：链完成/失败/让渡释放预留（node_id/frac/holder → released））
// 调度器
inline constexpr const char* ServiceChainSubmit        = "os2.mgmt.chain.submit";                // req/rep（v1.12/RFC-0012：同步执行并返回终态结果；不是仅表示接收的 ACK）
inline constexpr const char* ExecutionFeedback         = "os2.mgmt.chain.feedback";              // pub（v1.12/RFC-0012：每次提交恰好一条独立整链终态事实，正式测试不以请求应答代替该观察）
inline constexpr const char* ChainStepEvent            = "os2.mgmt.chain.step";                  // pub（v1.12/RFC-0012：逐步派发事实；dispatched/completed 使用 OS2-0000，failed 使用失败码，ts 为节点 Unix epoch ms）
inline constexpr const char* StepDispatch              = "os2.mgmt.chain.step.dispatch";         // req/rep（双总线隔离：调度器经管理面派发计算步到落位节点的执行代理，代理本地转调业务面服务（core 不经手业务数据）。节点特定主题——实际主题追加 .<node_id>（如 os2.mgmt.chain.step.dispatch.compute-01），各域执行代理仅 serve 自身节点主题以保证单应答路由）
// 运维管理器
inline constexpr const char* MetricIngest              = "os2.mgmt.ops.metric";                  // pub
inline constexpr const char* AlarmEvent                = "os2.mgmt.ops.alarm";                   // pub
inline constexpr const char* LogSliceExport            = "os2.mgmt.ops.logslice.export";         // req/rep
// 模型与数据管理器
inline constexpr const char* ModelSubmit               = "os2.mgmt.model.submit";                // req/rep（v1.4/RFC-0004（F-13 收编）：模型包提交与校验（model_id/kind/version/payload → passed/issues/compat），同 id 再提交过兼容门）
inline constexpr const char* ModelQuery                = "os2.mgmt.model.query";                 // req/rep（v1.4/RFC-0004（F-13 收编）：模型包查询（model_id → found+包体））
// 安全管理器
inline constexpr const char* PolicyCheck               = "os2.mgmt.security.policy.check";       // req/rep
inline constexpr const char* AuditEvent                = "os2.mgmt.security.audit";              // pub
// 应用商店与门户
inline constexpr const char* ArtifactPublish           = "os2.mgmt.store.artifact.publish";      // req/rep
inline constexpr const char* ActivationCommand         = "os2.mgmt.store.activation";            // req/rep
// 执行管理器
inline constexpr const char* ProcessReport             = "os2.mgmt.exec.process";                // pub（RFC-0017：EM 与服务进程共同上报；running 只能由 reporter=service 置位——EM 只知道 fork 成功）
inline constexpr const char* ProcessControl            = "os2.mgmt.exec.control";                // req/rep（RFC-0017：start 由 EM 执行（进程还没起，自己收不到）；stop/restart 服务进程自身也订阅）
// 业务软总线示例主题
inline constexpr const char* BizDataPrefix             = "os2.biz.";                             // prefix（业务数据不经管理面，见《架构说明》§5.2）
}  // namespace topics

// ---------------------------------------------------------------------------
// 通用工具：时间与 ID（trace_id/command_id 生成）
// ---------------------------------------------------------------------------
inline std::uint64_t now_ms() {
  return static_cast<std::uint64_t>(
      std::chrono::duration_cast<std::chrono::milliseconds>(
          std::chrono::system_clock::now().time_since_epoch()).count());
}

inline std::string gen_id(const std::string& prefix) {
  static thread_local std::mt19937_64 rng{std::random_device{}()};
  char buf[17];
  std::snprintf(buf, sizeof(buf), "%016llx",
                static_cast<unsigned long long>(rng()));
  return prefix + "-" + buf;
}

// ---------------------------------------------------------------------------
// 标准消息四元组（生成自 os2_common.idl，《架构说明》§6.2）
// 传输序列化在 PAL 适配器完成（wire v1 / DDS），字段即结构体成员。
// ---------------------------------------------------------------------------
struct Command {
  std::string   command_id;  // 命令唯一ID
  std::string   target_id;  // 目标对象
  std::string   command_type;  // 操作类型
  std::string   args_json;  // 参数（JSON）
  std::string   operator_id;  // 操作者（IDL 字段名 operator，C++ 保留字故加后缀）
  std::string   auth_context;  // 权限上下文
  std::uint64_t deadline_ms{0};
  std::string   trace_id;
};

struct Reply {
  std::string   command_id;
  std::string   result;  // success/failed
  std::string   reason_code;  // 契约错误码（OS2-xxxx，见 error-codes；M1 由 long 收敛为 string）
  std::string   effective_value;
  std::string   current_state;
  std::uint64_t cost_ms{0};
  std::uint64_t timestamp{0};
  std::string   trace_id;
  bool ok() const { return result == "success"; }
  static Reply success(const Command& c, std::string state = {}) {
    return Reply{c.command_id, "success", errc::OK, {}, std::move(state), 0, now_ms(), c.trace_id};
  }
  static Reply failure(const Command& c, std::string reason, std::string state = {}) {
    return Reply{c.command_id, "failed", std::move(reason), {}, std::move(state), 0, now_ms(), c.trace_id};
  }
};

struct Event {
  std::string   source;
  std::string   event_type;
  std::string   level;  // info/warn/error/critical
  std::string   state;
  std::string   reason;
  std::uint64_t timestamp{0};
  std::string   trace_id;
};

struct Metric {
  std::string   metric_name;
  std::string   labels_json;
  double        value{0};
  std::uint64_t timestamp{0};
  std::string   quality{"good"};
};

// ---------------------------------------------------------------------------
// 总线报文：统一用 type + kv 承载（typed struct ↔ Msg 在本契约层完成映射，
// 模块代码不手拼 kv 键名 —— 这保证换传输/序列化时模块代码零改动）。
// ---------------------------------------------------------------------------
struct Msg {
  std::string type;                             // 消息类型名，如 "Command"
  std::map<std::string, std::string> kv;        // 扁平字段
  std::string get(const std::string& k, const std::string& dflt = {}) const {
    auto it = kv.find(k); return it == kv.end() ? dflt : it->second;
  }
  std::uint64_t get_u64(const std::string& k, std::uint64_t dflt = 0) const {
    auto it = kv.find(k); return it == kv.end() ? dflt : std::strtoull(it->second.c_str(), nullptr, 10);
  }
  // 严格访问器（RFC-0005 支柱三）：缺失/非全量数值 → nullopt（区别于 get_u64 静默 0）；
  // 边界校验与"拒静默 0"读取路径用此，既有宽松 get_u64 保留不动（存量零改动）。
  std::optional<std::uint64_t> get_u64_checked(const std::string& k) const {
    auto it = kv.find(k);
    if (it == kv.end() || it->second.empty()) return std::nullopt;
    char* end = nullptr;
    unsigned long long v = std::strtoull(it->second.c_str(), &end, 10);
    if (end == it->second.c_str() || *end != '\0') return std::nullopt;
    return static_cast<std::uint64_t>(v);
  }
  std::optional<double> get_num_checked(const std::string& k) const {
    auto it = kv.find(k);
    if (it == kv.end() || it->second.empty()) return std::nullopt;
    char* end = nullptr;
    double v = std::strtod(it->second.c_str(), &end);
    if (end == it->second.c_str() || *end != '\0') return std::nullopt;
    return v;
  }
};

inline Msg to_msg(const Command& x) {
  return Msg{"Command", {{"command_id", x.command_id}, {"target_id", x.target_id}, {"command_type", x.command_type}, {"args_json", x.args_json}, {"operator", x.operator_id}, {"auth_context", x.auth_context}, {"deadline_ms", std::to_string(x.deadline_ms)}, {"trace_id", x.trace_id}}};
}
inline Command command_from(const Msg& m) {
  return Command{m.get("command_id"), m.get("target_id"), m.get("command_type"), m.get("args_json"), m.get("operator"), m.get("auth_context"), m.get_u64("deadline_ms"), m.get("trace_id")};
}
inline Msg to_msg(const Reply& x) {
  return Msg{"Reply", {{"command_id", x.command_id}, {"result", x.result}, {"reason_code", x.reason_code}, {"effective_value", x.effective_value}, {"current_state", x.current_state}, {"cost_ms", std::to_string(x.cost_ms)}, {"timestamp", std::to_string(x.timestamp)}, {"trace_id", x.trace_id}}};
}
inline Reply reply_from(const Msg& m) {
  return Reply{m.get("command_id"), m.get("result"), m.get("reason_code"), m.get("effective_value"), m.get("current_state"), m.get_u64("cost_ms"), m.get_u64("timestamp"), m.get("trace_id")};
}
inline Msg to_msg(const Event& x) {
  return Msg{"Event", {{"source", x.source}, {"event_type", x.event_type}, {"level", x.level}, {"state", x.state}, {"reason", x.reason}, {"timestamp", std::to_string(x.timestamp)}, {"trace_id", x.trace_id}}};
}
inline Event event_from(const Msg& m) {
  return Event{m.get("source"), m.get("event_type"), m.get("level"), m.get("state"), m.get("reason"), m.get_u64("timestamp"), m.get("trace_id")};
}
inline Msg to_msg(const Metric& x) {
  return Msg{"Metric", {{"metric_name", x.metric_name}, {"labels_json", x.labels_json}, {"value", std::to_string(x.value)}, {"timestamp", std::to_string(x.timestamp)}, {"quality", x.quality}}};
}
inline Metric metric_from(const Msg& m) {
  return Metric{m.get("metric_name"), m.get("labels_json"), std::strtod(m.get("value", "0").c_str(), nullptr), m.get_u64("timestamp"), m.get("quality")};
}

// ---------------------------------------------------------------------------
// 消息边界校验规则表（生成自 data_dictionary.yaml messages 段，RFC-0005 v1.5.0）
// 判定逻辑在 platform/msg_validator.hpp（数据/引擎分离）；opt-in 逐主题、缺省关。
// ---------------------------------------------------------------------------
namespace msgspec {
// 消息边界校验规则（生成自 data_dictionary.yaml messages 段，RFC-0005 v1.5.0）。
// 平台 MsgValidator（os2/platform/msg_validator.hpp）据此对进站 Msg 做类型/尺寸/拒收
// 校验；校验 opt-in 逐主题（bus.validate）、缺省关。此处仅数据表，判定逻辑在 MsgValidator。
enum class Kind : char { String = 's', Number = 'n', Enum = 'e' };
struct Field {
  const char* key;                 // 键名（线上 kv 键）
  Kind kind;                       // 期望类型
  bool opt;                        // 可选键（缺失不违规）
  bool pattern;                    // 动态键模板（前缀匹配，存在性不强制）
  const char* const* enum_tokens;  // 合法 token 集（Enum 专用，nullptr 结尾），否则 nullptr
};
struct TopicSpec {
  const char* topic;   // 主题名（=topics.yaml 名 / MsgValidator::for_topic 键）
  const char* dir;     // 方向：req/rep/pub
  const Field* fields;
  std::size_t count;
};

inline constexpr const char* const kTok_boolean[] = {"true", "false", nullptr};
inline constexpr const char* const kTok_chainStepState[] = {"dispatched", "completed", "failed", nullptr};
inline constexpr const char* const kTok_criticality[] = {"A", "B", "C", "D", nullptr};
inline constexpr const char* const kTok_domain[] = {"cai", "compute", "hmi", "ops", nullptr};
inline constexpr const char* const kTok_health[] = {"ok", "degraded", "down", nullptr};
inline constexpr const char* const kTok_processAction[] = {"start", "stop", "restart", nullptr};
inline constexpr const char* const kTok_processReporter[] = {"em", "service", nullptr};
inline constexpr const char* const kTok_processState[] = {"planned", "starting", "running", "stopping", "exited", "failed", nullptr};

inline constexpr Field kFields_ProcessReport_pub[] = {
  {"node_id", Kind::String, false, false, nullptr},
  {"instance_id", Kind::String, false, false, nullptr},
  {"service_id", Kind::String, false, false, nullptr},
  {"state", Kind::Enum, false, false, kTok_processState},
  {"reporter", Kind::Enum, false, false, kTok_processReporter},
  {"ts", Kind::String, false, false, nullptr},
  {"pid", Kind::String, true, false, nullptr},
  {"exit_code", Kind::String, true, false, nullptr},
  {"manifest", Kind::String, true, false, nullptr},
};

inline constexpr Field kFields_ProcessControl_req[] = {
  {"node_id", Kind::String, false, false, nullptr},
  {"instance_id", Kind::String, false, false, nullptr},
  {"action", Kind::Enum, false, false, kTok_processAction},
};

inline constexpr Field kFields_ProcessControl_rep[] = {
  {"result", Kind::String, false, false, nullptr},
  {"reason", Kind::String, false, false, nullptr},
  {"reason_code", Kind::String, false, false, nullptr},
};

inline constexpr Field kFields_ServiceRegister_req[] = {
  {"service_id", Kind::String, false, false, nullptr},
  {"node_id", Kind::String, false, false, nullptr},
  {"instance_id", Kind::String, false, false, nullptr},
  {"endpoint", Kind::String, false, false, nullptr},
  {"version", Kind::String, true, false, nullptr},
  {"domain", Kind::Enum, true, false, kTok_domain},
  {"criticality", Kind::Enum, true, false, kTok_criticality},
};

inline constexpr Field kFields_ServiceRegister_rep[] = {
  {"accepted", Kind::String, false, false, nullptr},
  {"reason", Kind::String, false, false, nullptr},
  {"reason_code", Kind::String, false, false, nullptr},
  {"epoch", Kind::String, true, false, nullptr},
};

inline constexpr Field kFields_ServiceHeartbeat_pub[] = {
  {"service_id", Kind::String, false, false, nullptr},
  {"node_id", Kind::String, false, false, nullptr},
  {"instance_id", Kind::String, false, false, nullptr},
  {"timestamp", Kind::Number, false, false, nullptr},
  {"health", Kind::Enum, false, false, kTok_health},
};

inline constexpr Field kFields_ResourceReport_pub[] = {
  {"node_id", Kind::String, false, false, nullptr},
  {"domain", Kind::Enum, false, false, kTok_domain},
  {"cpu_total", Kind::Number, false, false, nullptr},
  {"cpu_used", Kind::Number, false, false, nullptr},
  {"mem_total_mib", Kind::Number, false, false, nullptr},
  {"mem_used_mib", Kind::Number, false, false, nullptr},
  {"os", Kind::String, false, false, nullptr},
  {"health", Kind::Enum, false, false, kTok_health},
  {"ts", Kind::Number, false, false, nullptr},
  {"container_id", Kind::String, false, false, nullptr},
  {"boot_state", Kind::String, false, false, nullptr},
  {"modules", Kind::String, false, false, nullptr},
  {"payload", Kind::String, false, false, nullptr},
};

inline constexpr Field kFields_ServiceChainSubmit_req[] = {
  {"sc_xml", Kind::String, false, false, nullptr},
  {"trace_id", Kind::String, true, false, nullptr},
};

inline constexpr Field kFields_ServiceChainSubmit_rep[] = {
  {"chain_id", Kind::String, false, false, nullptr},
  {"trace_id", Kind::String, false, false, nullptr},
  {"success", Kind::Enum, false, false, kTok_boolean},
  {"reason_code", Kind::String, false, false, nullptr},
  {"cost_ms", Kind::Number, false, false, nullptr},
};

inline constexpr Field kFields_ChainStepEvent_pub[] = {
  {"chain_id", Kind::String, false, false, nullptr},
  {"trace_id", Kind::String, false, false, nullptr},
  {"seq", Kind::Number, false, false, nullptr},
  {"total", Kind::Number, false, false, nullptr},
  {"chain_node_id", Kind::String, false, false, nullptr},
  {"service", Kind::String, false, false, nullptr},
  {"assigned_node", Kind::String, false, false, nullptr},
  {"criticality", Kind::Enum, false, false, kTok_criticality},
  {"state", Kind::Enum, false, false, kTok_chainStepState},
  {"reason_code", Kind::String, false, false, nullptr},
  {"ts", Kind::Number, false, false, nullptr},
};

inline constexpr Field kFields_StepDispatch_req[] = {
  {"service", Kind::String, false, false, nullptr},
  {"node", Kind::String, false, false, nullptr},
  {"budget_ms", Kind::Number, true, false, nullptr},
  {"trace_id", Kind::String, true, false, nullptr},
};

inline constexpr Field kFields_StepDispatch_rep[] = {
  {"result", Kind::String, false, false, nullptr},
  {"reason_code", Kind::String, true, false, nullptr},
  {"served_by", Kind::String, true, false, nullptr},
  {"trace_id", Kind::String, true, false, nullptr},
};

inline constexpr Field kFields_ExecutionFeedback_pub[] = {
  {"chain_id", Kind::String, false, false, nullptr},
  {"trace_id", Kind::String, false, false, nullptr},
  {"success", Kind::Enum, false, false, kTok_boolean},
  {"reason_code", Kind::String, false, false, nullptr},
  {"cost_ms", Kind::Number, false, false, nullptr},
  {"completed_nodes", Kind::String, false, false, nullptr},
};

inline constexpr Field kFields_ServiceCatalogQuery_req[] = {
  {"prefix", Kind::String, true, false, nullptr},
  {"domain", Kind::Enum, true, false, kTok_domain},
  {"offset", Kind::Number, true, false, nullptr},
  {"limit", Kind::Number, true, false, nullptr},
};

inline constexpr Field kFields_ServiceCatalogQuery_rep[] = {
  {"service_ids", Kind::String, false, false, nullptr},
  {"total", Kind::Number, false, false, nullptr},
  {"next_offset", Kind::Number, true, false, nullptr},
  {"health.<service>", Kind::Enum, false, true, kTok_health},
  {"endpoint.<service>", Kind::String, false, true, nullptr},
  {"instances.<service>", Kind::Number, false, true, nullptr},
  {"nodes.<service>", Kind::String, false, true, nullptr},
  {"lease_ms.<record>", Kind::Number, false, true, nullptr},
};

inline constexpr Field kFields_ServiceInstanceStateQuery_req[] = {
  {"prefix", Kind::String, true, false, nullptr},
  {"domain", Kind::Enum, true, false, kTok_domain},
};

inline constexpr Field kFields_ServiceInstanceStateQuery_rep[] = {
  {"instance_keys", Kind::String, false, false, nullptr},
  {"total", Kind::Number, false, false, nullptr},
  {"evaluated_at_ms", Kind::Number, false, false, nullptr},
  {"service_id.<record>", Kind::String, false, true, nullptr},
  {"instance_id.<record>", Kind::String, false, true, nullptr},
  {"node_id.<record>", Kind::String, false, true, nullptr},
  {"health_state.<record>", Kind::Enum, false, true, kTok_health},
  {"reason_code.<record>", Kind::String, false, true, nullptr},
  {"lease_ms.<record>", Kind::Number, false, true, nullptr},
  {"last_seen_ms.<record>", Kind::Number, false, true, nullptr},
  {"reported_timestamp_ms.<record>", Kind::Number, false, true, nullptr},
};

inline constexpr Field kFields_ImpactQuery_req[] = {
  {"failed_nodes", Kind::String, true, false, nullptr},
  {"failed_links", Kind::String, true, false, nullptr},
  {"failed_services", Kind::String, true, false, nullptr},
  {"runtime_down_services", Kind::String, true, false, nullptr},
  {"runtime_evaluated_at_ms", Kind::Number, true, false, nullptr},
};

inline constexpr Field kFields_ImpactQuery_rep[] = {
  {"accepted", Kind::Enum, false, false, kTok_boolean},
  {"reason_code", Kind::String, false, false, nullptr},
  {"input_digest", Kind::String, false, false, nullptr},
  {"snapshot_sha256", Kind::String, false, false, nullptr},
  {"runtime_evaluated_at_ms", Kind::Number, false, false, nullptr},
  {"affected_nodes", Kind::String, false, false, nullptr},
  {"affected_services", Kind::String, false, false, nullptr},
  {"affected_chains", Kind::String, false, false, nullptr},
  {"paths", Kind::String, false, false, nullptr},
  {"unknown_inputs", Kind::String, false, false, nullptr},
};

inline constexpr Field kFields_ResourceInventoryQuery_req[] = {
  {"query", Kind::String, true, false, nullptr},
  {"domain", Kind::Enum, true, false, kTok_domain},
};

inline constexpr Field kFields_ResourceInventoryQuery_rep[] = {
  {"node_ids", Kind::String, false, false, nullptr},
  {"os.<node>", Kind::String, false, true, nullptr},
  {"cid.<node>", Kind::String, false, true, nullptr},
  {"boot.<node>", Kind::String, false, true, nullptr},
  {"modules.<node>", Kind::String, false, true, nullptr},
  {"payload.<node>", Kind::String, false, true, nullptr},
  {"score.<node>", Kind::Number, false, true, nullptr},
};

inline constexpr Field kFields_ResourceReserve_req[] = {
  {"node_id", Kind::String, false, false, nullptr},
  {"frac", Kind::Number, false, false, nullptr},
  {"holder", Kind::String, false, false, nullptr},
  {"ttl_ms", Kind::Number, false, false, nullptr},
};

inline constexpr Field kFields_ResourceReserve_rep[] = {
  {"accepted", Kind::String, false, false, nullptr},
  {"reason", Kind::String, true, false, nullptr},
};

inline constexpr Field kFields_ResourceRelease_req[] = {
  {"node_id", Kind::String, false, false, nullptr},
  {"frac", Kind::Number, false, false, nullptr},
  {"holder", Kind::String, false, false, nullptr},
};

inline constexpr Field kFields_ResourceRelease_rep[] = {
  {"released", Kind::String, false, false, nullptr},
};

inline constexpr Field kFields_ModelSubmit_req[] = {
  {"model_id", Kind::String, false, false, nullptr},
  {"kind", Kind::String, false, false, nullptr},
  {"version", Kind::String, false, false, nullptr},
  {"payload", Kind::String, false, false, nullptr},
};

inline constexpr Field kFields_ModelSubmit_rep[] = {
  {"model_id", Kind::String, false, false, nullptr},
  {"passed", Kind::String, false, false, nullptr},
  {"issues", Kind::String, false, false, nullptr},
  {"compat", Kind::String, true, false, nullptr},
};

inline constexpr Field kFields_ModelQuery_req[] = {
  {"model_id", Kind::String, false, false, nullptr},
};

inline constexpr Field kFields_ModelQuery_rep[] = {
  {"found", Kind::String, false, false, nullptr},
  {"model_id", Kind::String, true, false, nullptr},
  {"kind", Kind::String, true, false, nullptr},
  {"version", Kind::String, true, false, nullptr},
  {"payload", Kind::String, true, false, nullptr},
};

inline constexpr Field kFields_ProgramControlCommand_req[] = {
  {"command_id", Kind::String, false, false, nullptr},
  {"target_id", Kind::String, false, false, nullptr},
  {"command_type", Kind::String, false, false, nullptr},
  {"args_json", Kind::String, true, false, nullptr},
  {"operator", Kind::String, true, false, nullptr},
  {"auth_context", Kind::String, true, false, nullptr},
  {"deadline_ms", Kind::Number, true, false, nullptr},
  {"trace_id", Kind::String, true, false, nullptr},
};

inline constexpr TopicSpec kMsgSpecs[] = {
  {"ProcessReport", "pub", kFields_ProcessReport_pub, 9},
  {"ProcessControl", "req", kFields_ProcessControl_req, 3},
  {"ProcessControl", "rep", kFields_ProcessControl_rep, 3},
  {"ServiceRegister", "req", kFields_ServiceRegister_req, 7},
  {"ServiceRegister", "rep", kFields_ServiceRegister_rep, 4},
  {"ServiceHeartbeat", "pub", kFields_ServiceHeartbeat_pub, 5},
  {"ResourceReport", "pub", kFields_ResourceReport_pub, 13},
  {"ServiceChainSubmit", "req", kFields_ServiceChainSubmit_req, 2},
  {"ServiceChainSubmit", "rep", kFields_ServiceChainSubmit_rep, 5},
  {"ChainStepEvent", "pub", kFields_ChainStepEvent_pub, 11},
  {"StepDispatch", "req", kFields_StepDispatch_req, 4},
  {"StepDispatch", "rep", kFields_StepDispatch_rep, 4},
  {"ExecutionFeedback", "pub", kFields_ExecutionFeedback_pub, 6},
  {"ServiceCatalogQuery", "req", kFields_ServiceCatalogQuery_req, 4},
  {"ServiceCatalogQuery", "rep", kFields_ServiceCatalogQuery_rep, 8},
  {"ServiceInstanceStateQuery", "req", kFields_ServiceInstanceStateQuery_req, 2},
  {"ServiceInstanceStateQuery", "rep", kFields_ServiceInstanceStateQuery_rep, 11},
  {"ImpactQuery", "req", kFields_ImpactQuery_req, 5},
  {"ImpactQuery", "rep", kFields_ImpactQuery_rep, 10},
  {"ResourceInventoryQuery", "req", kFields_ResourceInventoryQuery_req, 2},
  {"ResourceInventoryQuery", "rep", kFields_ResourceInventoryQuery_rep, 7},
  {"ResourceReserve", "req", kFields_ResourceReserve_req, 4},
  {"ResourceReserve", "rep", kFields_ResourceReserve_rep, 2},
  {"ResourceRelease", "req", kFields_ResourceRelease_req, 3},
  {"ResourceRelease", "rep", kFields_ResourceRelease_rep, 1},
  {"ModelSubmit", "req", kFields_ModelSubmit_req, 4},
  {"ModelSubmit", "rep", kFields_ModelSubmit_rep, 4},
  {"ModelQuery", "req", kFields_ModelQuery_req, 1},
  {"ModelQuery", "rep", kFields_ModelQuery_rep, 5},
  {"ProgramControlCommand", "req", kFields_ProgramControlCommand_req, 8},
};
inline constexpr std::size_t kMsgSpecCount = sizeof(kMsgSpecs) / sizeof(kMsgSpecs[0]);
}  // namespace msgspec

}  // namespace os2
